vim.keymap.set("n", "<F7>",  ":FloatermNew<CR>")
vim.keymap.set("n", "<F7>",  "<C-\\><C-n>:FloatermNew<CR>")
vim.keymap.set("n", "<F8>",  ":FloatermPrev<CR>")
vim.keymap.set("t", "<F8>",  "<C-\\><C-n>:FloatermPrev<CR>")
vim.keymap.set("n", "<F9>",  ":FloatermNext<CR>")
vim.keymap.set("t", "<F9>",  "<C-\\><C-n>:FloatermNext<CR>")
vim.keymap.set("n", "<F12>", ":FloatermToggle<CR>")
vim.keymap.set("t", "<F12>", "<C-\\><C-n>:FloatermToggle<CR>")
